Algoritmo "armazenamento"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/06/2021
Var
   n, a , b : inteiro


Inicio
   escreval("Digite um numero: ")
   leia(n)
   se(n >= 0) entao
      a <- n
      Escreval("O numero : " ,a, " é varialvel de A ")
   senao
      b <- n
      escreval("O numero : " ,b, "E varialvel de B")
   fimse



Fimalgoritmo