Algoritmo "Calcular_valor_salario"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/05/2021
Var
   Salario, dias_trabalhados: real
   salario_base: real


Inicio
   salario_base <- 300.50
   Escreva ("Escreva quantos dias voce trabalhou: ")
   leia(dias_trabalhados)

   salario <- salario_base * dias_trabalhados
   escreva("Seu salario recebido foi de " ,salario , " R$")


Fimalgoritmo