Algoritmo "Contador"
//
//
// Descrição   : Quantidade de números existentes de 50 até 100! (função)
// Autor(a)    : Katianne Araujo dos Santos
// Data atual  : 05/06/2021
var
   contador:inteiro

inicio
 Escreval("A quantidade de numeros existentes entre 50 e 100 são :")
   contador <- 50
   enquanto (contador <=100)faca

      escreva(contador:6)
      contador <-contador+1

   Fimenquanto
   Escreval("")
   Escreval("Fim da contagem!!! ")

fimalgoritmo