Algoritmo "Erro_Programador"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/06/2021

Var
   Erros, Programas, contador : inteiro

inicio

   Erros := 1;
   Programas := 2 * 13;

   Para contador := 2 Até Programas Faça
      Erros := Erros * 2;
   Fimpara;
   Escreva("Número de erros ==>",Erros)

fimalgoritmo