Algoritmo "LerVetores"
//
//
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/05/2021
Var
   x : inteiro
   valores : vetor [1..5] de inteiro


Inicio
   para x de 1 até 5 faça
      Escreval("Digite um valor: ")
      leia(valores[x])

   fimpara

   para x de 1 até 5 faça
      Escreval("Os numero digitados foram : " , valores[x])
   fimpara

Fimalgoritmo