Algoritmo "meu nome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/05/2021
Var
nome : Caractere
idade : Inteiro

Inicio

 Escreva ("Digite seu nome: ")
 Leia (nome)
 Escreval ("Muito prazer, " ,nome)
 
 
 Escreva("Quantos anos voce tem ", nome, " ? ")
 Leia(idade)
 Escreva ("Entendir voce tem " ,idade, " anos ")

Fimalgoritmo