Algoritmo "múltiplo_de_três"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/06/2021

Var

   num, contador : inteiro

inicio
   Para contador := 1 Até 100 Faça
      Escreval("Digite um números ")
      Leia(num)

      Se (num MOD 3 = 0 ) Então

         leia(num)
      Fimse
   Fimpara
   limpatela
   escreva("Entre os 100 numeros o mutiplo de 3 é")
    Escreval(num)
fimalgoritmo
