Algoritmo "operadoresrelacionais"
//
//
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/05/2021
Var
   a, b, c: inteiro


Inicio
   a <- 2
   b <- 3
   c <- 5

   Escreval (a > b)
   Escreval (a = b)
   Escreval (a <> b)
   Escreval (a > 2)
   Escreval (a >= 2)
   Escreval (c = a + b)
   Escreval (c = b ^ a)
   Escreval (b >= c % 2)
   Escreval (1 = c % 2)


Fimalgoritmo