Algoritmo "saber idade"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/05/2021
Var
   ano_atual, ano_nasc, idade:   inteiro


Inicio
   Escreva ("O ano que estamos? :")
   Leia(ano_atual)
   Escreva ("Em que ano eu nascir? :")
   Leia (ano_nasc)
   idade <- ano_atual - ano_nasc
   Escreva ("MInha idade é:" , idade)

Fimalgoritmo