Algoritmo "Teste vetor"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/05/2021
Var
    vet : vetor [1..6] de inteiro
    i: inteiro
    


Inicio
para i de 1 até 6 faça
 escreva ("Digite " , i , "º valor : ")
 leia( vet[i])
 fimpara
 para i de 1 até 6 faça
  escreval ("[" ,vet[i] , "]")
  fimpara



Fimalgoritmo