Algoritmo "valor_em_parcelas"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/05/2021
Var
   valor_em , parcelas , valor: real


Inicio
   Escreva ("Digite o valor que voce que de emprestimo : ")
   Leia(valor_em )


   Escreva ("Qunatas parcelas voce quer dividir: ")
   Leia(parcelas)
   valor <- (valor_em + (20*10)) /10
   Escreva ("O valor das parcelas é : " , valor)
Fimalgoritmo