Algoritmo "valores2"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/05/2021
Var
   n1, n2: Inteiro M: Real


Inicio
   Escreva ("Informe um numero: ")
   Leia(n1)
   Escreva ("Informe outro numero: ")
   Leia (n2)

   M <- (n1 + n2)/2
   Escreva("A media entre", n1, " e " , n2, " é ", M)


Fimalgoritmo